# Generated by Django 5.1.1 on 2025-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Not Started', max_length=20)),
                ('Assignees', models.CharField(max_length=255)),
                ('Tags', models.CharField(choices=[('High priority', 'High priority'), ('Medium priority', 'Medium priority'), ('Low priority', 'Low priority')], default='Medium Priority', max_length=20)),
                ('File', models.FileField(blank=True, null=True, upload_to='static/files')),
            ],
        ),
    ]
