# Generated by Django 5.1.1 on 2025-04-06 22:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudgetNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reportname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('plannedQuantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usedQuantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remainingQuantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceExpnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reportname', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalBudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Totalexpenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Notes', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceTransactionsNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=250)),
                ('Status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Not Started', max_length=20)),
                ('Assignees', models.CharField(blank=True, max_length=255, null=True)),
                ('DueDate', models.DateField(default=None)),
                ('Tags', models.CharField(choices=[('High priority', 'High priority'), ('Medium priority', 'Medium priority'), ('Low priority', 'Low priority')], default='Medium Priority', max_length=20)),
                ('File', models.FileField(blank=True, null=True, upload_to='static/files')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UName', models.CharField(blank=True, max_length=255, null=True)),
                ('Workers', models.CharField(choices=[('0-50', '0-50'), ('50-150', '50-150'), ('150-300', '150-300'), ('300-Above', '300-Above')], default='0-50', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customeruser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customeruser_Permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetName', models.CharField(default=None, max_length=255)),
                ('Totalbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('AmountSpent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remainingbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('name', models.CharField(default=None, max_length=255)),
                ('total', models.FloatField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(choices=[('Income', 'Income'), ('Expenses', 'Expenses')], default='Income', max_length=255)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterIntoExistingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.BigIntegerField()),
                ('TypeOfWork', models.CharField(choices=[('Clients', 'Clients'), ('Finance', 'Finance'), ('Worker', 'Worker'), ('Q.Assurance', 'Q.Assurance'), ('Supplier', 'Supplier'), ('Site Supervisor', 'Site Supervisor')], default='Clients', max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QualityStatus', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=50, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.financematerial')),
                ('worker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject')),
            ],
        ),
        migrations.AddField(
            model_name='financematerial',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject'),
        ),
        migrations.CreateModel(
            name='supervisorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Startingdate', models.DateField(blank=True, default=None, null=True)),
                ('Budget', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('End_date', models.DateField(blank=True, default=None, null=True)),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisorrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('name', models.CharField(default=None, max_length=255)),
                ('amount', models.CharField(default=None, max_length=255)),
                ('date', models.DateField(default=None)),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('Quantity_Needed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Quantity_Available', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_Per_Quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Total_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construction.financematerial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Sick', 'Sick'), ('On Leave', 'On Leave')], default='Present', max_length=255)),
                ('check_in', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('check_out', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('workinghrs', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('PerfomedWork', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialname', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Quantity_taken', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Quantity_usage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Remaining', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Usage_date', models.DateField(blank=True, default=None, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Construction.workerattendance')),
            ],
        ),
    ]
