# Generated by Django 5.1.1 on 2025-04-06 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreport',
            name='amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='supplierreport',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.financematerial'),
        ),
        migrations.AddField(
            model_name='supplierreport',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='supplierreport',
            name='total',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
