# Generated by Django 5.1.1 on 2025-03-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='status',
            new_name='Status',
        ),
    ]
