# Generated by Django 5.1.1 on 2025-03-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0002_rename_status_clientmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='Assignees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
