# Generated by Django 5.1.1 on 2025-03-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0002_financecategories_financereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financereport',
            name='category',
        ),
    ]
