# Generated by Django 5.1.1 on 2025-04-07 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0002_supplierreport_amount_supplierreport_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierreport',
            name='material',
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
