# Generated by Django 5.1.1 on 2025-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0003_alter_clientmodel_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='DueDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
