# Generated by Django 5.1.1 on 2025-03-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0003_remove_financereport_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financereport',
            name='user',
        ),
    ]
