# Generated by Django 5.1.1 on 2025-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0004_remove_financereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='financereport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
