# Generated by Django 5.1.1 on 2025-04-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0004_supplierreport_supplierstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassurance',
            name='TypeOfWork',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='qualityassurance',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='qualityassurance',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
