# Generated by Django 5.1.1 on 2025-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0004_clientmodel_duedate_alter_clientmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
    ]
