# Generated by Django 5.1.1 on 2025-03-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0005_alter_clientmodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterIntoExistingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=250)),
                ('Pcode', models.CharField(max_length=255)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Phone', models.BigIntegerField(max_length=20)),
                ('TypeOfWork', models.CharField(choices=[('Clients', 'Clients'), ('Finance', 'Finance'), ('Worker', 'Worker'), ('Q.Assurance', 'Q.Assurance'), ('Supplier', 'Supplier'), ('Site Supervisor', 'Site Supervisor')], default='Clients', max_length=20)),
            ],
        ),
    ]
