# Generated by Django 5.2 on 2025-04-11 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0005_qualityassurance_typeofwork_qualityassurance_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudgetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetName', models.CharField(default=None, max_length=255)),
                ('Totalbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('AmountSpent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remainingbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
