# Generated by Django 5.1.1 on 2025-03-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0006_financeexpenditure_financeexpnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeexpenditure',
            old_name='Material',
            new_name='material',
        ),
    ]
