# Generated by Django 5.1.1 on 2025-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0006_registerintoexistingproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerintoexistingproject',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
