# Generated by Django 5.2 on 2025-04-11 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0006_financebudgetapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssuranceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.BigIntegerField(default=None)),
                ('TypeOfWork', models.CharField(default=None, max_length=255)),
                ('QualityStatus', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=50, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject')),
            ],
        ),
    
    ]
