# Generated by Django 5.2 on 2025-04-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0007_qualityassurancestatus_delete_qualityassurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QualityAssuranceStatus',
        ),
    ]
