# Generated by Django 5.1.1 on 2025-03-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0007_rename_material_financeexpenditure_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financecategories',
            old_name='name',
            new_name='Reportname',
        ),
        migrations.RenameField(
            model_name='financereport',
            old_name='comments',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='financereport',
            old_name='name',
            new_name='Reportname',
        ),
        migrations.RenameField(
            model_name='financereport',
            old_name='actual_expenses',
            new_name='TotalBudg',
        ),
        migrations.RenameField(
            model_name='financereport',
            old_name='budget',
            new_name='Totalexpenses',
        ),
    ]
