# Generated by Django 5.1.1 on 2025-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0008_rename_name_financecategories_reportname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financereport',
            name='generated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
