# Generated by Django 5.2 on 2025-04-11 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0009_qualityassurancestatus_delete_qualityassurance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('SupplierStatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('Quantity_Needed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Quantity_Available', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_Per_Quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Total_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('FinalStatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
     
    ]
