# Generated by Django 5.1.1 on 2025-03-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0010_alter_financereport_generated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financereport',
            old_name='TotalBudg',
            new_name='TotalBudget',
        ),
    ]
