# Generated by Django 5.1.1 on 2025-03-27 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0011_rename_totalbudg_financereport_totalbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudgetNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('AmountSpent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remainingbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
