# Generated by Django 5.1.1 on 2025-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0012_financebudgetno_financebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='financebudget',
            name='BudgetName',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
