# Generated by Django 5.1.1 on 2025-03-30 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0017_financematerialname_financematerial_qualityassurance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=50, null=True)),
                ('QuantityNeeded', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('QuantityAvailable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricePerQuantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('TotalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.financematerial')),
            ],
        ),
    ]
