# Generated by Django 5.1.1 on 2025-03-30 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0018_supplierreport_workerattendance_workermaterialusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierreport',
            old_name='QuantityAvailable',
            new_name='Quantity_Available',
        ),
        migrations.RenameField(
            model_name='supplierreport',
            old_name='QuantityNeeded',
            new_name='Quantity_Needed',
        ),
        migrations.RenameField(
            model_name='supplierreport',
            old_name='TotalPrice',
            new_name='Total_Price',
        ),
        migrations.RenameField(
            model_name='supplierreport',
            old_name='pricePerQuantity',
            new_name='price_Per_Quantity',
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
  ]
