# Generated by Django 5.1.1 on 2025-04-02 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0020_supplierreport_user_workerattendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Startingdate', models.DateField(blank=True, default=None, null=True)),
                ('Budget', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('End_date', models.DateField(blank=True, default=None, null=True)),
                ('ProjectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Supervisor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisorrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Amount', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('ProjectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Supervisor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject')),
            ],
        ),
     
    ]
