# Generated by Django 5.1.1 on 2025-04-03 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0021_supervisorproject_supervisorrequest_workerattendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorproject',
            old_name='Supervisor',
            new_name='name',
        ),
  ]
