# Generated by Django 5.1.1 on 2025-04-03 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0023_rename_amount_supervisorrequest_numfields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorrequest',
            old_name='Supervisor',
            new_name='name',
        ),
      
    ]
