# Generated by Django 5.1.1 on 2025-04-03 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0026_remove_supervisorrequest_projectname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='amount',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='material',
            field=models.CharField(default=None, max_length=255),
        ),
       
    ]
