# Generated by Django 5.1.1 on 2025-04-04 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0028_rename_material_supervisorrequest_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorproject',
            name='ProjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisorproject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject'),
        ),
    
    ]
