# Generated by Django 5.1.1 on 2025-04-04 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0030_supervisorrequest_projectname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorrequest',
            name='TotalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supervisorrequest',
            name='pricePerQuantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='ProjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='Supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject'),
        ),
      
    ]
