# Generated by Django 5.1.1 on 2025-04-04 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0031_supervisorrequest_totalamount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorrequest',
            old_name='TotalAmount',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='supervisorrequest',
            old_name='pricePerQuantity',
            new_name='price',
        ),
    
    ]
