# Generated by Django 5.1.1 on 2025-04-04 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0033_workerattendance_workermaterialusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financematerial',
            name='QuantityNeeded',
        ),
        migrations.RemoveField(
            model_name='financematerial',
            name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='financematerial',
            name='pricePerQuantity',
        ),
        migrations.RemoveField(
            model_name='financematerial',
            name='projectName',
        ),
        migrations.AddField(
            model_name='financematerial',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='financematerial',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.financematerialname'),
        ),
        migrations.AddField(
            model_name='financematerial',
            name='supervisorrequest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.supervisorrequest'),
        ),
        migrations.AddField(
            model_name='financematerial',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Construction.registerintoexistingproject'),
        ),
      
    ]
